// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.146.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Notification.Domain
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Globalization;
    using global::System.Linq;

    using global::Naos.Protocol.Domain;

    using global::OBeautifulCode.Equality.Recipes;
    using global::OBeautifulCode.Type;
    using global::OBeautifulCode.Type.Recipes;

    using static global::System.FormattableString;

    [Serializable]
    public partial class ProcessSendNotificationSagaOp : IModel<ProcessSendNotificationSagaOp>
    {
        /// <summary>
        /// Determines whether two objects of type <see cref="ProcessSendNotificationSagaOp"/> are equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are equal; otherwise false.</returns>
        public static bool operator ==(ProcessSendNotificationSagaOp left, ProcessSendNotificationSagaOp right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
            {
                return false;
            }

            var result = left.Equals(right);

            return result;
        }

        /// <summary>
        /// Determines whether two objects of type <see cref="ProcessSendNotificationSagaOp"/> are not equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are not equal; otherwise false.</returns>
        public static bool operator !=(ProcessSendNotificationSagaOp left, ProcessSendNotificationSagaOp right) => !(left == right);

        /// <inheritdoc />
        public bool Equals(ProcessSendNotificationSagaOp other)
        {
            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (ReferenceEquals(other, null))
            {
                return false;
            }

            var result = this.NotificationTrackingCodeId.IsEqualTo(other.NotificationTrackingCodeId)
                      && this.ChannelToOperationsMonitoringInfoMap.IsEqualTo(other.ChannelToOperationsMonitoringInfoMap);

            return result;
        }

        /// <inheritdoc />
        public override bool Equals(object obj) => this == (obj as ProcessSendNotificationSagaOp);

        /// <inheritdoc />
        public override int GetHashCode() => HashCodeHelper.Initialize()
            .Hash(this.NotificationTrackingCodeId)
            .Hash(this.ChannelToOperationsMonitoringInfoMap)
            .Value;

        /// <inheritdoc />
        public new ProcessSendNotificationSagaOp DeepClone() => (ProcessSendNotificationSagaOp)this.DeepCloneInternal();

        /// <summary>
        /// Deep clones this object with a new <see cref="NotificationTrackingCodeId" />.
        /// </summary>
        /// <param name="notificationTrackingCodeId">The new <see cref="NotificationTrackingCodeId" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ProcessSendNotificationSagaOp" /> using the specified <paramref name="notificationTrackingCodeId" /> for <see cref="NotificationTrackingCodeId" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002: DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ProcessSendNotificationSagaOp DeepCloneWithNotificationTrackingCodeId(long notificationTrackingCodeId)
        {
            var result = new ProcessSendNotificationSagaOp(
                                 notificationTrackingCodeId,
                                 this.ChannelToOperationsMonitoringInfoMap?.ToDictionary(k => (IDeliveryChannel)DeepCloneInterface(k.Key), v => (IReadOnlyList<ChannelOperationMonitoringInfo>)v.Value?.Select(i2 => i2?.DeepClone()).ToList()));

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="ChannelToOperationsMonitoringInfoMap" />.
        /// </summary>
        /// <param name="channelToOperationsMonitoringInfoMap">The new <see cref="ChannelToOperationsMonitoringInfoMap" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="ProcessSendNotificationSagaOp" /> using the specified <paramref name="channelToOperationsMonitoringInfoMap" /> for <see cref="ChannelToOperationsMonitoringInfoMap" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002: DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public ProcessSendNotificationSagaOp DeepCloneWithChannelToOperationsMonitoringInfoMap(IReadOnlyDictionary<IDeliveryChannel, IReadOnlyList<ChannelOperationMonitoringInfo>> channelToOperationsMonitoringInfoMap)
        {
            var result = new ProcessSendNotificationSagaOp(
                                 this.NotificationTrackingCodeId,
                                 channelToOperationsMonitoringInfoMap);

            return result;
        }

        /// <inheritdoc />
        protected override OperationBase DeepCloneInternal()
        {
            var result = new ProcessSendNotificationSagaOp(
                                 this.NotificationTrackingCodeId,
                                 this.ChannelToOperationsMonitoringInfoMap?.ToDictionary(k => (IDeliveryChannel)DeepCloneInterface(k.Key), v => (IReadOnlyList<ChannelOperationMonitoringInfo>)v.Value?.Select(i2 => i2?.DeepClone()).ToList()));

            return result;
        }

        private static object DeepCloneInterface(object value)
        {
            object result;

            if (ReferenceEquals(value, null))
            {
                result = null;
            }
            else
            {
                var type = value.GetType();

                if (type.IsValueType)
                {
                    result = value;
                }
                else if (value is string valueAsString)
                {
                    result = valueAsString.DeepClone();
                }
                else if (value is global::System.Version valueAsVersion)
                {
                    result = valueAsVersion.DeepClone();
                }
                else if (value is global::System.Uri valueAsUri)
                {
                    result = valueAsUri.DeepClone();
                }
                else
                {
                    var deepCloneableInterface = typeof(IDeepCloneable<>).MakeGenericType(type);

                    if (deepCloneableInterface.IsAssignableFrom(type))
                    {
                        var deepCloneMethod = deepCloneableInterface.GetMethod(nameof(IDeepCloneable<object>.DeepClone));

                        result = deepCloneMethod.Invoke(value, null);
                    }
                    else
                    {
                        throw new NotSupportedException(Invariant($"I do not know how to deep clone an object of type '{type.ToStringReadable()}'"));
                    }
                }
            }

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        public override string ToString()
        {
            var result = Invariant($"Naos.Notification.Domain.ProcessSendNotificationSagaOp: NotificationTrackingCodeId = {this.NotificationTrackingCodeId.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, ChannelToOperationsMonitoringInfoMap = {this.ChannelToOperationsMonitoringInfoMap?.ToString() ?? "<null>"}.");

            return result;
        }
    }
}