// --------------------------------------------------------------------------------------------------------------------
// <copyright file="NotificationDummyFactory.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.50)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using FakeItEasy;
using OBeautifulCode.AutoFakeItEasy;
using System;

namespace Naos.Notification.Domain.Test
{
    /// <summary>
    /// A Dummy Factory for types in <see cref="Naos.Notification.Domain"/>.
    /// </summary>
#if !NaosNotificationSolution
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Notification.Domain.Test", "See package version number")]
    internal
#else
    public
#endif
    class NotificationDummyFactory : DefaultNotificationDummyFactory
    {
        public NotificationDummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}